Revert to old manifest buildpack syntax
While running the deployment in our pipeline we had the following
error:

    error: Error reading manifest file:
    The following manifest fields cannot be used with legacy push: buildpacks

Probably we need to upgrade the version of the containers used
in our pipelines.

But this is unrelated the feature implemented in this PR, so
we will revert it for the time being and fix it later.